---
title: "Jack Yan"
output: 
  html_document:
    toc: true
    toc_float: true

---


Here is a pdf version of my [resume](_resume_jack_yan.pdf).


# EDUCATION

**COLUMBIA UNIVERSITY**

**MS IN BIOSTATISTICS**

Expected May 2020 | New York, NY 

Cum. GPA: N/A\  

**NANJING AGRICULTURAL UNIVERSITY**

**BS IN BIOLOGY**

Grad. Jun 2018 | Nanjing, China

Cum. GPA: 3.83 / 4.0

**UNIVERSITY OF CALIFORNIA**

**EXCHANGE STUDENT**

2016 | Davis, CA

Cum. GPA: 3.75 / 4.0

# EXPERIENCE

**NANJING AGRICULTRUAL UNIVERSITY**

STATISTICIAN INTERN

Nov 2017 – Jun 2018 | Nanjing, China

*  Conducted data cleaning, visualization and statistical inference on microRNA gene expression data.
*  Used Python and JavaScript to scrape over 1000 observations of microRNA parametric data.

**NATIONAL DRUG CLINICAL TRIAL CENTER**

STATISTICIAN INTERN

May 2017 – Aug 2017 | Nanjing, China

*  Worked on clinical trial design and statistical analysis with several clinical trial and experiment reports.
*  Attended routine trainings and 5 consulting events on clinical research statistical analysis.
*  Assisted in preliminary stage of a trial about adult mesenchymal stem cell therapy for diminished ovarian reserve patients; got familiarized with Electric Data Capture System.

**UNIVERSITY OF CALIFORNIA, DAVIS**

RESEARCH ASSISTANT

Sep 2016 – Dec 2016 | Davis, CA

*  Practiced molecular biology techniques including plasmidextraction, transformation, enzyme digestion, DNA gel electrophoresis, and primer design.
*  Learnt to do BLAST and plasmid sequence annotation.
*  Assisted to work on a project of sunflower circadian regulation and heliotropism.

# RESEARCH

**NAU SOIL MICROBIOLOGY LAB**

HEAD UNDERGRAD RESEACHER

Apr 2016 – Jun 2017 | Nanjing, China

*  Designed and conducted experiments to analyze impacts of soil factors and three soil types on the structure of soil bacterial communities.
*  Analyzed bacterial diversity by calculating Shannon Index, Simpson Index, and Dominance Index and clustering analysis; discussed the impacts of all factors and compared with publications.

**NAU PLANT PHYSIOLOGY LAB**

HEAD UNDERGRAD RESEARCH

Dec 2016 – Jun 2017 | Nanjing, China

*  Studied hydrogen-rich water’s effect on nitrate reductase activity, vitamin C content and degradation of pesticides of types of fruit and vegetable.
*  Designed and prepared a vegetable preservation box that controllably produce and spray hydrogen-rich water; tested its applicability and safety.
*  Prepared documents for patent application (authorized) and PPT / reports for contest.

